# ===================================================================
# НАСТРОЙКА ПОДКЛЮЧЕНИЯ К СУБД ORACLE
# ===================================================================
# Дефолтный урл для запуска БЕЗ докера (внутри докера мы его переопределяем)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=SYSTEM
spring.datasource.password=0508
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===================================================================
# НАСТРОЙКИ ПУЛА СОЕДИНЕНИЙ HIKARICP
# ===================================================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

# ===================================================================
# НАСТРОЙКИ JPA / HIBERNATE И ТРАССИРОВКА SQL
# ===================================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Возвращаем строгий и безопасный Enterprise-режим валидации схемы СУБД
spring.jpa.hibernate.ddl-auto=validate

# Включаем логирование реальных значений (Binding Parameters) в SQL-запросах
logging.level.org.hibernate.orm.jdbc.bind=trace

# ===================================================================
# СТРАТЕГИЯ ИМЕНОВАНИЯ: ЗАЩИТА РЕГИСТРА ДЛЯ ORACLE
# ===================================================================
# Отключаем принудительный перевод имен таблиц и колонок в нижний регистр.
# Эти строки приказывают Hibernate брать имена из аннотаций @Table и @Column буква в букву!
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
