# ===================================================================
# НАСТРОЙКА ПОДКЛЮЧЕНИЯ К СУБД ORACLE
# ===================================================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/petproject7
spring.datasource.username=SYSTEM
spring.datasource.password=0508
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===================================================================
# НАСТРОЙКИ ПУЛА СОЕДИНЕНИЙ HIKARICP
# ===================================================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

# ===================================================================
# НАСТРОЙКИ JPA / HIBERNATE И ТРАССИРОВКА SQL
# ===================================================================
# Включаем вывод сгенерированного SQL прямо в консоль приложения
spring.jpa.show-sql=true

# Делаем SQL-логи красивыми и читаемыми (с отступами и переносами)
spring.jpa.properties.hibernate.format_sql=true

# Режим "validate" проверяет, соответствует ли твоя таблица в Oracle аннотациям в Subscriber.java
spring.jpa.hibernate.ddl-auto=validate

# ХАРДКОД ДЛЯ SRE: Включаем логирование реальных значений (Binding Parameters) в SQL-запросах
logging.level.org.hibernate.orm.jdbc.bind=trace
