# ===================================================================
# НАСТРОЙКА ПОДКЛЮЧЕНИЯ К СУБД ORACLE
# ===================================================================
# Дефолтный урл для запуска БЕЗ докера (внутри докера мы его переопределяем)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=SYSTEM
spring.datasource.password=0508
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===================================================================
# НАСТРОЙКИ ПУЛА СОЕДИНЕНИЙ HIKARICP
# ===================================================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

# ===================================================================
# НАСТРОЙКИ JPA / HIBERNATE И ТРАССИРОВКА SQL
# ===================================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# МЕНЯЕМ НА "update": если таблицы нет или регистр букв отличается — Hibernate сам всё подправит!
spring.jpa.hibernate.ddl-auto=update

# Включаем трассировку реальных значений параметров
logging.level.org.hibernate.orm.jdbc.bind=trace
